In [2]:
import numpy as np

In [7]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
print(a.shape)

(3, 5)


In [12]:
print(a.ndim)

2


In [13]:
print(a.dtype)

int64


In [14]:
print(a.dtype.name)

int64


In [15]:
a.itemsize #单个元素的字节大小

8

In [16]:
a.size

15

In [17]:
type(a)

numpy.ndarray

In [18]:
arr = np.array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [20]:
arr1 = np.array([(1.5,1,4),(4,2,5)])
arr1

array([[1.5, 1. , 4. ],
       [4. , 2. , 5. ]])

In [21]:
arr2 = np.array([[1.5,3.5,2.5],[3.5,6.5,2.5]],dtype = int)
arr2

array([[1, 3, 2],
       [3, 6, 2]])

In [23]:
arr_zeros = np.zeros((3,2)) # np.zeros(3,2)这个写法是错误的
arr_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
arr_ones = np.ones((3,2))
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
arr_empty = np.empty((3,2))
arr_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
arr_arange = np.arange(5,10,1) #[起始数字,末尾数字)，步长
arr_arange

array([5, 6, 7, 8, 9])

In [32]:
arr_arange_float = np.arange(5,10,0.5) #接受浮点数
arr_arange_float

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [36]:
from numpy import pi
arr_lin = np.linspace(0,5,5) #[起始数字，末尾数字]，个数
arr_pi = np.linspace(0,2*pi, 100)
arr_f = np.sin(arr_pi)
arr_f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [38]:
arr_range = np.arange(5)
arr_range < 3

array([ True,  True,  True, False, False])

In [60]:
arr_a = np.array([[1,1],[1,0]])
arr_b = np.array([[2,0],[3,4]])
print('arr_a:\n',arr_a)
print('arr_b:\n',arr_b)
print('arr_a + arr_b: \n', arr_a+arr_b)
print('arr_a * arr_b: \n', arr_a * arr_b) #逐元素相乘
print('arr_a @ arr_b: \n', arr_a @ arr_b) #矩阵相乘
print('arr_a.dot(arr_b): \n', arr_a.dot(arr_b)) #跟@的功能一样

arr_a:
 [[1 1]
 [1 0]]
arr_b:
 [[2 0]
 [3 4]]
arr_a + arr_b: 
 [[3 1]
 [4 4]]
arr_a * arr_b: 
 [[2 0]
 [3 0]]
arr_a @ arr_b: 
 [[5 4]
 [2 0]]
arr_a.dot(arr_b): 
 [[5 4]
 [2 0]]


In [57]:
arr_range = np.arange(5)
print('数组：',arr_range)
print('求和：',arr_range.sum())
print('最小值：',arr_range.min())
print('最大值：',arr_range.max())

数组： [0 1 2 3 4]
求和： 10
最小值： 0
最大值： 4


In [73]:
arr_axis_sample = np.arange(15).reshape(3,5)
print('arr_axis_sample:')
print(arr_axis_sample)
print('axis = 0:')
print(arr_axis_sample.sum(axis = 0))
print('axis = 1:')
print(arr_axis_sample.sum(axis = 1))
print('min:')
print(arr_axis_sample.min())
print('min(axis = 0):')
print(arr_axis_sample.min(axis = 0))

arr_axis_sample:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
axis = 0:
[15 18 21 24 27]
axis = 1:
[10 35 60]
min:
0
min(axis = 0):
[0 1 2 3 4]


In [78]:
arr_arange = np.arange(15)
print('arr_arange:')
print(arr_arange)
print('arr_arange[2:5]:')
print(arr_arange[2:5])
print('arr_arange[:5:2]:')
print(arr_arange[:5:2])
print('arr_arange[-1]:')
print(arr_arange[::-1])

arr_arange:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
arr_arange[2:5]:
[2 3 4]
arr_arange[:5:2]:
[0 2 4]
arr_arange[-1]:
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [90]:
arr_arange_b = np.arange(15).reshape(3,5)
print('arr_arange_b:')
print(arr_arange_b)
print('arr_arange_b[0:2,1]:')
print(arr_arange_b[0:2,1])
print('arr_arange_b[:,1]:')
print(arr_arange_b[:,1])
print('for:')
for row in arr_arange_b:
    print(row)
print('flat:')
for element in arr_arange_b.flat:
    print(element)

arr_arange_b:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
arr_arange_b[0:2,1]:
[1 6]
arr_arange_b[:,1]:
[ 1  6 11]
for:
[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
flat:
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
ravel():
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [101]:
arr_arange_c = np.arange(15).reshape(3,5)
print('arr_arange_c:')
print(arr_arange_c)
print('ravel():')
print(arr_arange_c.ravel())
print('T:')
print(arr_arange_c.T)
print('resize:')
arr_arange_c.resize((5,3))
print(arr_arange_c)
print('-1:')
print(arr_arange_c.reshape(3,-1))

arr_arange_c:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
ravel():
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
T:
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
resize:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
-1:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [105]:
arr_a = np.array([[1,2],[3,4]])
print('arr_a:')
print(arr_a)
arr_b = np.array([[5,6],[7,8]])
print('arr_b:')
print(arr_b)
print('vstack:')
print(np.vstack((arr_a,arr_b)))
print('hstack:')
print(np.hstack((arr_a,arr_b)))

arr_a:
[[1 2]
 [3 4]]
arr_b:
[[5 6]
 [7 8]]
vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack:
[[1 2 5 6]
 [3 4 7 8]]


In [107]:
arr_a = np.array([[1,2],[3,4]])
print('arr_a:')
print(arr_a)
arr_b = np.array([[5,6],[7,8]])
print('arr_b:')
print(arr_b)
print('concatenate:')
print(np.concatenate((arr_a,arr_b),axis = 1))

arr_a:
[[1 2]
 [3 4]]
arr_b:
[[5 6]
 [7 8]]
concatenate:
[[1 2 5 6]
 [3 4 7 8]]


In [114]:
arr_arange_c = np.arange(15).reshape(3,5)
print('arr_arange_c:')
print(arr_arange_c)
print('hsplit:')
print(np.hsplit(arr_arange_c,5))
print('vsplit:')
print(np.vsplit(arr_arange_c,3))

arr_arange_c:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
hsplit:
[array([[ 0],
       [ 5],
       [10]]), array([[ 1],
       [ 6],
       [11]]), array([[ 2],
       [ 7],
       [12]]), array([[ 3],
       [ 8],
       [13]]), array([[ 4],
       [ 9],
       [14]])]
vsplit:
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]])]


In [123]:
arr_arange_c = np.arange(15).reshape(3,5)
print('arr_arange_c:')
print(arr_arange_c)
arr_arange_d = arr_arange_c.view()
print('view:')
print('is: ',arr_arange_d is arr_arange_c)
print('id: ', id(arr_arange_d) == id(arr_arange_c))
print('base: ', arr_arange_d.base is arr_arange_c)

arr_arange_c:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
view:
is:  False
id:  False
base:  False
